name: Build APK
on:
  workflow_dispatch: # هذا الأمر هو المسؤول عن إظهار زر التشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: npm install
      - run: npx eas-cli build --platform android --profile preview --local
